version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root#nl6
      MYSQL_DATABASE: tq_mobile
      MYSQL_USER: nlkf
      MYSQL_PASSWORD: nlkf#nl6
    ports:
      - "3344:3306"
    volumes:
      - /mydata/docker/mysqlRedis/data/mysql/data:/var/lib/mysql
      - /mydata/docker/mysqlRedis/data/mysql/conf:/etc/mysql/conf.d
      - /mydata/docker/mysqlRedis/data/mysql/logs:/var/log/mysql
    networks:
      - app-network

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6336:6379"
      - "8811:8001"  # RedisInsight 管理界面
    volumes:
      - /mydata/docker/mysqlRedis/data/redis/data:/data  # 数据持久化目录
      - /mydata/docker/mysqlRedis/data/redis/backups:/backups  # 备份目录
      - /mydata/docker/mysqlRedis/data/redis/etc/redis-stack.conf:/etc/redis-stack/redis-stack.conf
    environment:
      - REDIS_STACK_DATA_DIR=/data
      - REDIS_BACKUP_DIR=/backups
      - REDIS_PASSWORD=qcgL20mlMdJEDfbj  # 设置访问密码
    command:
      - redis-stack-server
      - /etc/redis-stack/redis-stack.conf
      - --save 60 1  # 60秒内至少有1个key改变则保存
      - --appendonly yes  # 启用AOF持久化
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge